name: NSIS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building EQDiet-Setup.exe using NSIS
        uses: joncloud/makensis-action@v3.4
        with:
          script-file: EQDiet.nsi